### ISSUE TITLE
Lock Screen Limit & Passcode Error

### ISSUE THREAD

**Issue by KartikSubramaniam** [prscX/react-native-lock-screen#2]
Hi,

The current lock screen does not have any limit to total number of characters to be entered and moreover when we enter the lock screen we can directly push enter without entering any passcode.

Thanks

**Comment by prscX** [comment]
Thanks @KartikSubramaniam for sharing the thoughts. I completely agree with idea, in coming days I will look into the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @KartikSubramaniam, 

I have enabled the requested feature in latest release. Thanks of providing your valuable feedback.

Thanks
</ Pranav >
