### ISSUE TITLE
Error when entering wrong pin

### ISSUE THREAD

**Issue by chri633x** [prscX/react-native-lock-screen#7]
Hi,

I get the error below when I enter a wrong pincode (mode is set to 'Verify'). It works fine when the pin is correct. Any ideas how to solve this? Im running it on my iPhone SE with 'Expo Client'.

![photo6001434914999872533](https://user-images.githubusercontent.com/42170756/43766101-e292476a-9a31-11e8-9e98-376b370b299e.jpg)

Thanks

**Comment by prscX** [comment]
Thanks @chri633x for raising the issue.

Looks like `RNToasty` library is not linked. Please execute below command for the same:

`react-native link react-native-toasty`

Please let me know in case you still face the same issue.

Thanks
</ Pranav >
